Rework pkgcat

diff --git a/pkgcat b/pkgcat
--- a/pkgcat
+++ b/pkgcat
@@ -1,48 +1,45 @@
 #!/bin/sh
 # Script by Ypnose - http://ypnose.org
 # Query PKGBUILD online
-# TODO: REWORK DAT UGLY CRAP!
 
-usage() {
-	printf "%s\n" "Usage: ${0##*/} [-a]"
-	printf "%s\n" "  OPTARG:"
-	printf "%s\n" "    -a 	Search package on AUR."
-	printf "%s\n\n" "If OPTARG is empty, pkgcat will query package on [core], [extra] and then [community] repos."
-}
+# With bash
+# LET="${2:0:2}"
+LET="$(echo $2 | cut -c -2)"
+AUR="https://aur.archlinux.org/packages/${LET}/${2}/PKGBUILD"
+URLP="https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/${1}"
+URLC="https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/${1}"
 
-if [ -z "$1" ] || [ "$1" = -h ]; then
-	usage
+if [ -z "$1" ] || [ "$1" = "-h" ]; then
+	printf "%s\n%s\n" "usage: ${0##*/} [-a] package" \
+	"    -a    Search package on AUR."
 	exit 1
 fi
 
-LET="$(echo $2 | awk '{print substr ($0, 0, 2)}')"
-AUR="https://aur.archlinux.org/packages/$LET/$2/PKGBUILD"
-URLP="https://projects.archlinux.org/svntogit/packages.git/plain/trunk/PKGBUILD?h=packages/$1"
-URLC="https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/$1"
-
 if [ "$1" = "-a" ] && [ "$#" -eq 2 ]; then
-	printf "\033[0;32m%s\033[0m\n" "Searching on AUR..."
-	if [ -z "$(curl -s $AUR | awk '/404/')" ]; then
+	printf "%s\n" "Searching on AUR..."
+	if [ -z "$(curl -s $AUR | grep '404')" ]; then
 		printf "\n%s\n" "$(curl -s $AUR)"
-		exit 0
+		exit
 	else
-		printf "\033[0;31m%s\033[0m\n" "Package not found!"
+		printf "%s\n" "Package not found on AUR!" >&2
 		exit 1
 	fi
 fi
 
-printf "\033[0;32m%s\033[0m\n" "Trying core / extra repo..."
+printf "%s\n" "Trying core / extra repo..."
+REPO="packages"
 if [ "$(curl -s $URLP | awk 'NR == 1 {print $1}')" != "<!DOCTYPE" ]; then
 	printf "\n%s\n" "$(curl -s $URLP)"
-	exit 0
+	exit
 else
-	printf "\033[0;31m%s\033[0m\n" "Package not found in core / extra"
-	printf "\033[0;32m%s\033[0m\n" "Trying community repo..."
+	printf "%s\n%s\n" "Package not found in core / extra" \
+	"Trying community repo..."
+	REPO="community"
 	if [ "$(curl -s $URLC | awk 'NR == 1 {print $1}')" != "<!DOCTYPE" ]; then
 		printf "\n%s\n" "$(curl -s $URLC)"
-		exit 0
+		exit
 	else
-		printf "\033[0;31m%s\033[0m\n" "Package not found!"
+		printf "%s\n" "Package not found!" >&2
 		exit 1
 	fi
 fi
